"""IELTS Speaking recall questions extracted from the May-August PDF question bank.

The source is a scanned candidate-recall booklet. Obvious OCR and grammar defects in
question wording have been cleaned while preserving the original tested topics.
"""


PART1_WORK_QUESTIONS = [
    "Where do you work?",
    "How do you usually spend your day at work?",
    "Have you found anything interesting at work recently?",
    "Is there anything you do not like about your job?",
    "What is the most interesting part of your work?",
    "What are your future work plans?",
]


PART1_STUDY_QUESTIONS = [
    "What do you study?",
    "Where do you study?",
    "How do you usually spend your day when you are studying?",
    "Have you learned anything interesting in your studies recently?",
    "What kinds of things do you not like about your studies?",
    "What is the most interesting part of your major?",
    "How will you use what you have learned in the future?",
]


PDF_PART1_SECONDARY_TOPICS = [
    {
        "name": "where you live",
        "questions": [
            "Where do you live now?",
            "Do you live in an apartment or somewhere else?",
            "Do you think it is an interesting place to live?",
            "How long have you lived in your area?",
            "What do you enjoy most about living there?",
            "Is your area busy or quiet?",
            "Have you met many of your neighbours?",
        ],
    },
    {
        "name": "hometown",
        "questions": [
            "Where is your hometown?",
            "Is it a big city or a small place?",
            "How long did you live there?",
        ],
    },
    {
        "name": "singing",
        "questions": [
            "Did you like singing when you were a child?",
            "Do you like singing now?",
            "Do you ever sing in the car?",
            "Do you like listening to other people sing?",
            "Did you learn to sing at school?",
        ],
    },
    {
        "name": "music",
        "questions": [
            "Do you like music?",
            "What kinds of music do you listen to?",
            "Do you prefer sad or happy music?",
            "Does happy music make you feel more excited?",
            "Is it easy to learn music?",
            "Did you have music lessons at school?",
        ],
    },
    {
        "name": "watches",
        "questions": [
            "Do you wear a watch in your daily life?",
            "What kind of watch do you have?",
            "Has anyone ever given you a watch as a gift?",
            "What kind of watches do people around you like to wear?",
        ],
    },
    {
        "name": "parks and gardens",
        "questions": [
            "What kind of parks and gardens did you like as a child?",
            "Do you enjoy visiting parks and gardens now?",
            "Should there be more parks and gardens in your city?",
            "Is there a famous park or garden that you want to visit?",
        ],
    },
    {
        "name": "tidiness",
        "questions": [
            "Were you a tidy person when you were a child?",
            "Are you a tidy person now?",
            "Do you keep your space tidy when you work or study?",
            "What do you think of people who do not care about tidiness?",
            "What do you think of people who are overly concerned about tidiness?",
        ],
    },
    {
        "name": "headphones",
        "questions": [
            "How often do you wear headphones?",
            "Do you think headphones are useful?",
            "Are headphones comfortable to wear?",
            "Are headphones popular in your country?",
            "In what situations should people not wear headphones?",
        ],
    },
    {
        "name": "websites",
        "questions": [
            "Do you often use websites?",
            "Which websites do you usually use?",
            "Do you prefer searching for information on websites or in books?",
            "Would you like to create your own website in the future?",
        ],
    },
    {
        "name": "telling jokes",
        "questions": [
            "Do you like telling jokes?",
            "Do you have friends who love telling jokes?",
            "What are some common comedy shows in your country?",
            "Do you often joke with your friends?",
            "Do you like being joked about?",
        ],
    },
    {
        "name": "science",
        "questions": [
            "Do you like science?",
            "Did you learn about science at school?",
            "Do you enjoy watching science programmes?",
            "What area of science do you know about?",
        ],
    },
    {
        "name": "teachers",
        "questions": [
            "Do you have a favourite teacher?",
            "Which teacher do you remember more, one from primary school or secondary school?",
            "Do you think being a teacher is a good career choice?",
            "Do you still keep in touch with any former teachers?",
        ],
    },
    {
        "name": "social media",
        "questions": [
            "Do your friends and family use social media?",
            "Do people in your country find social media useful?",
            "Do you spend too much time on social media?",
            "When did you start using social media?",
        ],
    },
    {
        "name": "cars",
        "questions": [
            "Would you rather be the driver or the passenger?",
            "Are there many cars on the roads in your city?",
            "Did you go on a long car journey when you were a child?",
            "Would you like to own a very expensive car?",
        ],
    },
    {
        "name": "clothes",
        "questions": [
            "What kind of clothes do you like to wear?",
            "Do you wear different clothes at weekends?",
            "Do you buy clothes because of the brand?",
            "What colours of clothes do you dislike?",
        ],
    },
    {
        "name": "shopping",
        "questions": [
            "Do you often go shopping?",
            "Do you prefer online or offline shopping?",
            "Do you compare prices before making a purchase?",
            "Have you ever returned a product you bought?",
        ],
    },
    {
        "name": "space travel",
        "questions": [
            "Did you learn about space or the universe at school?",
            "Would you like to know more about space and the stars?",
            "Have you watched any films about space?",
            "Would you like to travel into space on holiday?",
            "Are you interested in space travel?",
        ],
    },
    {
        "name": "food",
        "questions": [
            "What was your favourite food when you were a child?",
            "Has the kind of food you like changed as you have grown older?",
            "Do you eat different foods at different times of the year?",
            "Do you like eating with other people?",
            "Is eating together important in your country?",
        ],
    },
    {
        "name": "pets and animals",
        "questions": [
            "Did you want a pet when you were a child?",
            "Would you like to have a pet in the future?",
            "Would you prefer to keep a pet indoors or outdoors?",
            "Do you see many birds and animals where you live?",
            "Have you ever been to a zoo?",
            "What animal is your country famous for?",
        ],
    },
    {
        "name": "typing",
        "questions": [
            "How often do you type on a keyboard?",
            "Did you learn how to type at school?",
            "When did you learn how to type on a keyboard?",
            "Which is easier for you, typing or writing by hand?",
            "Would you like to improve your typing skills?",
        ],
    },
    {
        "name": "stages of life",
        "questions": [
            "Are you satisfied with your age now?",
            "What did you enjoy most about your childhood?",
            "What is the most important thing you have done so far?",
            "At what age do people enjoy life most?",
            "What would you like to do five years from now?",
        ],
    },
    {
        "name": "long walks",
        "questions": [
            "Did you go for long walks when you were a child?",
            "How often do you walk to the shops?",
            "Are there many parks near where you live?",
            "Do people in your country enjoy walking in parks?",
            "Where would you go for a long walk if you had the chance?",
        ],
    },
    {
        "name": "reading carefully",
        "questions": [
            "What kinds of things do you have to read carefully?",
            "Do you usually read things carefully or quickly?",
            "Do you read more carefully on paper or on a screen?",
            "Why do some people not read messages carefully?",
        ],
    },
    {
        "name": "morning routine",
        "questions": [
            "Do you get up early in the morning?",
            "Did you get up early when you were younger?",
            "What do you do every morning?",
            "What is your favourite morning of the week?",
        ],
    },
    {
        "name": "gifts",
        "questions": [
            "What kinds of gifts do you like to receive?",
            "What gifts did you like when you were younger?",
            "Have you received any gifts recently?",
            "Do you enjoy giving people gifts?",
            "Is buying gifts online a good idea?",
        ],
    },
    {
        "name": "team sports",
        "questions": [
            "Have you ever played a team sport?",
            "Is your local sports team famous?",
            "Are team sports popular in your country?",
            "Would you like to try a new team sport?",
            "Do you enjoy watching team sports?",
        ],
    },
    {
        "name": "buildings",
        "questions": [
            "Are there many tall buildings where you live?",
            "Have you ever taken a photo of a building?",
            "What kind of building would you like to live in?",
            "Is there a famous building you would like to visit?",
            "What is the tallest building in your city?",
        ],
    },
    {
        "name": "travelling and views",
        "questions": [
            "When you travel, do you usually look at the view?",
            "Did you travel to a faraway place as a child?",
            "Do you prefer mountain views or ocean views?",
            "Do you take photos of beautiful views?",
            "Would you hang a picture of a beautiful view in your home?",
        ],
    },
    {
        "name": "free-time activities",
        "questions": [
            "What was your favourite free-time activity as a child?",
            "Do you prefer doing free-time activities alone or with others?",
            "What activities do you enjoy in your free time now?",
            "Is there an activity you would like to try in the future?",
        ],
    },
    {
        "name": "memory",
        "questions": [
            "Is it easy for you to remember people's names?",
            "Do you remember things easily when studying or working?",
            "Would you like to have a better memory?",
            "Have you ever forgotten something very important?",
        ],
    },
]


DEFAULT_PART3_FALLBACK = [
    "Why might people have different opinions about this topic?",
    "How has this aspect of life changed in recent years?",
    "Are younger and older people likely to think differently about it?",
    "How might this topic develop in the future?",
]


def _card(title, opening, points, follow_up):
    return {
        "title": title,
        "prompt": (
            f"{opening}\n\nYou should say:\n"
            + "\n".join(f"- {point}" for point in points)
        ),
        "follow_up": follow_up,
        "part3": list(DEFAULT_PART3_FALLBACK),
    }


PDF_CUE_CARDS = [
    _card(
        "food eaten on a special occasion",
        "Describe a kind of food that you ate on a special occasion.",
        ["what it was", "what the occasion was", "why you ate it", "how you felt about it"],
        "Would you like to eat this food again on another special occasion?",
    ),
    _card(
        "a difficult decision with a good result",
        "Describe a difficult decision you made that had a good result.",
        ["what the decision was", "why it was difficult", "what helped you decide", "why it had a good result"],
        "Would you make the same decision again?",
    ),
    _card(
        "a person with a medical career",
        "Describe a person you know who has chosen a career in the medical field.",
        ["who this person is", "what this person does", "why this person chose this career", "how you feel about this person"],
        "Would you ever consider working in the medical field?",
    ),
    _card(
        "a good place to live",
        "Describe a place you have visited that you think is a good place to live.",
        ["where it is", "what you know about it", "what people can do there", "why you recommend it as a place to live"],
        "Would you personally like to live there?",
    ),
    _card(
        "a tall building you like or dislike",
        "Describe a tall building in your city that you like or dislike.",
        ["where it is", "what it is used for", "what it looks like", "why you like or dislike it"],
        "Would you like to go inside this building?",
    ),
    _card(
        "a successful businessperson",
        "Describe a person you know who runs a successful business.",
        ["how you know this person", "what the business does", "how long it has operated", "why the business is successful"],
        "Would you like to run a similar business?",
    ),
    _card(
        "a person who enjoys growing plants",
        "Describe a person you know who enjoys growing plants.",
        ["how you know this person", "what plants they grow", "where they grow them", "why they enjoy growing plants"],
        "Would you like to grow plants with this person?",
    ),
    _card(
        "a live sports match",
        "Describe a live sports match you have watched.",
        ["what it was", "when you watched it", "what it was like", "how you felt about it"],
        "Would you like to watch this sport live again?",
    ),
    _card(
        "a piece of local news",
        "Describe a piece of local news that interested people.",
        ["what it was about", "where you saw or heard it", "who was involved", "why people were interested"],
        "Did this news affect you personally?",
    ),
    _card(
        "a technology problem",
        "Describe a problem with technology that you encountered.",
        ["what the problem was", "when and where it happened", "how it was solved", "how you felt about it"],
        "Could you solve the same problem by yourself now?",
    ),
    _card(
        "getting up very early",
        "Describe a time when you had to get up very early.",
        ["what time you got up", "where you were", "why you had to get up early", "how you felt about it"],
        "Do you normally find it easy to get up early?",
    ),
    _card(
        "a home you liked visiting but would not live in",
        "Describe a home that you liked visiting but would not want to live in.",
        ["where it is", "what it is like", "why you visited it", "why you would not like to live there"],
        "Would you like to visit this home again?",
    ),
    _card(
        "a long-held ambition",
        "Describe an ambition you have had for a long time.",
        ["what it is", "how you developed this ambition", "what you must do to achieve it", "how you feel about it"],
        "Do you think you will achieve this ambition?",
    ),
    _card(
        "a childhood friend",
        "Describe a friend from childhood whom you remember well.",
        ["who this friend is", "how you met", "what you did together", "why you remember this friend so well"],
        "Are you still in contact with this friend?",
    ),
    _card(
        "a time you changed your plans",
        "Describe a time when you had to change your plans.",
        ["when it happened", "why the plan changed", "what the new plan was", "how you felt about the change"],
        "Did the new plan work out well?",
    ),
    _card(
        "an interesting social-media video",
        "Describe an interesting video you watched on social media.",
        ["when and where you saw it", "what it was about", "why it was interesting", "how you felt about it"],
        "Would you share this video with other people?",
    ),
    _card(
        "a time you changed your opinion",
        "Describe a time when you changed your opinion.",
        ["when it happened", "what your original opinion was", "why you changed it", "how you felt afterwards"],
        "Do you think your new opinion will change again?",
    ),
    _card(
        "a holiday place you recommend",
        "Describe a place you visited on holiday that you would recommend.",
        ["where it is", "why you went there", "what you did", "why you recommend it"],
        "Would you return to this place for another holiday?",
    ),
    _card(
        "a place where you felt bored",
        "Describe a place you visited where you felt bored.",
        ["where it was", "when you went there", "what you did there", "why you found it boring"],
        "Would anything make this place more interesting?",
    ),
    _card(
        "a person who achieved something difficult",
        "Describe a person you know who successfully achieved something difficult.",
        ["who this person is", "what they achieved", "why it was difficult", "how you felt about the achievement"],
        "Did this person inspire you to attempt something difficult?",
    ),
    _card(
        "an environmental protection law",
        "Describe an environmental protection law that you would like to introduce.",
        ["what it would require", "how you learned about the issue", "who would benefit", "how you feel about this law"],
        "Do you think most people would support this law?",
    ),
    _card(
        "an important decision made slowly",
        "Describe a time when you had to make an important decision carefully.",
        ["what the decision was", "how you made it", "why it was important", "why you think it was the right decision"],
        "Did anyone help you make this decision?",
    ),
    _card(
        "giving a talk to many people",
        "Describe a time when you had to give a talk to a large group of people.",
        ["who you spoke to", "what the talk was about", "why you gave it", "how you felt about giving it"],
        "Would you feel more confident giving the same talk now?",
    ),
    _card(
        "doing something with other people",
        "Describe something you did with one or more people.",
        ["what you did", "who you did it with", "how long it took", "how you felt about working together"],
        "Would you choose to work with these people again?",
    ),
    _card(
        "an animal story",
        "Describe a story involving an animal from a film or book.",
        ["what the story is about", "when and where you encountered it", "which animals appear", "how you felt about it"],
        "Would you recommend this story to a child?",
    ),
    _card(
        "a person who did not reply to your message",
        "Describe a person who did not reply to one of your messages.",
        ["who this person is", "what message you sent", "whether they eventually replied", "how you felt about it"],
        "Did you contact this person again?",
    ),
    _card(
        "an advertisement featuring a famous person",
        "Describe an advertisement featuring a famous person.",
        ["what it advertised", "when and where you saw it", "what the famous person did", "how you felt about it"],
        "Did the advertisement make you want to buy the product?",
    ),
    _card(
        "a person who is good at learning languages",
        "Describe a person who is good at learning languages.",
        ["who this person is", "how you know them", "which languages they learned", "why they are good at language learning"],
        "Would you like to learn a language with this person?",
    ),
    _card(
        "a family member who made you proud",
        "Describe a time when you felt proud of a family member.",
        ["who the family member is", "what they did", "where and when it happened", "why you felt proud"],
        "Did you tell this person that you were proud?",
    ),
    _card(
        "a time you could not use your phone",
        "Describe a time when you were not allowed to use your phone.",
        ["when it was", "where you were", "why you could not use it", "how you felt about it"],
        "Was it difficult to manage without your phone?",
    ),
    _card(
        "a perfect future job",
        "Describe a perfect job you would like to have in the future.",
        ["what the job is", "how you learned about it", "what skills it requires", "why it would be perfect for you"],
        "What is the first step you could take towards this job?",
    ),
    _card(
        "an occasion when many people smiled",
        "Describe an occasion when you saw many people smiling.",
        ["where and when it happened", "who you were with", "what happened", "why you remember it"],
        "Did you take any photographs on this occasion?",
    ),
    _card(
        "a famous person you would like to meet",
        "Describe a famous person you would like to meet.",
        ["who this person is", "what they do", "what they are famous for", "why you want to meet them"],
        "What would you ask this person?",
    ),
    _card(
        "a person who enjoys helping others",
        "Describe a person you know who enjoys helping other people.",
        ["who this person is", "what they do to help", "how often they help", "why they enjoy helping others"],
        "Has this person ever helped you?",
    ),
    _card(
        "a useful program or app",
        "Describe a program or app on your computer or phone.",
        ["what it is and what it does", "how you learned about it", "when you use it", "how you feel about using it"],
        "Would you recommend this app to other people?",
    ),
    _card(
        "a movie you enjoyed",
        "Describe a movie you enjoyed watching.",
        ["where and when you saw it", "who you watched it with", "what it was about", "why you enjoyed it"],
        "Would you watch this movie again?",
    ),
    _card(
        "a time you used your imagination",
        "Describe a time when you needed to use your imagination.",
        ["what you needed to do", "why imagination was necessary", "whether it was easy or difficult", "how you felt about the result"],
        "Do you often use imagination in your daily life?",
    ),
    _card(
        "an interesting road trip",
        "Describe a car, motorbike, or bicycle trip that you think would be interesting.",
        ["where you want to go", "who you want to go with", "how easy or difficult it would be", "why this form of transport would make it interesting"],
        "Which of these forms of transport would you choose?",
    ),
    _card(
        "a quiet place you enjoyed visiting",
        "Describe a quiet place that you enjoyed visiting.",
        ["where it is", "when you went there", "what you did there", "why you enjoyed its quietness"],
        "Would you like to spend more time in this place?",
    ),
    _card(
        "a person who learned without a teacher",
        "Describe a person who learned something new without a teacher.",
        ["who this person is", "what they learned", "whether it was easy", "how you feel about their achievement"],
        "Would you try to learn the same skill independently?",
    ),
    _card(
        "a person who is good at planning",
        "Describe a person you know who is good at planning things.",
        ["who this person is", "how you know them", "what they plan well", "why they are good at planning"],
        "Has this person ever helped you make a plan?",
    ),
    _card(
        "a child who enjoys painting or drawing",
        "Describe a child you know who enjoys painting or drawing.",
        ["who the child is", "what they paint or draw", "how often they do it", "why they enjoy it"],
        "Would you display one of this child's pictures in your home?",
    ),
    _card(
        "a good place for shopping",
        "Describe a place you go to that is good for shopping.",
        ["where it is", "how often you go", "what you do there", "why it is a good place for shopping"],
        "Would you recommend this place to a visitor?",
    ),
    _card(
        "working briefly in another country",
        "Describe a place in another country where you would like to work for a short time.",
        ["where it is", "how you know about it", "what work you would do", "why you want to work there briefly"],
        "How long would you like to work there?",
    ),
    _card(
        "a time you gave advice",
        "Describe a time when you gave advice to someone.",
        ["when it happened and who you advised", "what the advice was", "why you gave it", "how the person felt about it"],
        "Did this person follow your advice?",
    ),
    _card(
        "technology you would like to buy",
        "Describe a piece of technology, other than a phone, that you would like to buy.",
        ["what it is", "how much it costs", "what you would use it for", "why you would like to buy it"],
        "Do you think you will buy it soon?",
    ),
    _card(
        "an event with music you disliked",
        "Describe an event you attended where some music was played that you did not like.",
        ["what the event was", "who you went with", "why you attended", "why you disliked the music"],
        "Did the music affect your enjoyment of the event?",
    ),
    _card(
        "a TV or online programme",
        "Describe a TV or online programme that you enjoy watching.",
        ["what it is about", "how often you watch it", "which country it comes from", "why you enjoy it"],
        "Would you recommend this programme to a friend?",
    ),
    _card(
        "paying more than expected",
        "Describe a time when you had to pay more than expected for something.",
        ["what you bought", "how you felt when you saw the price", "what you did", "why it cost more than expected"],
        "Would you buy the same thing again?",
    ),
    _card(
        "a city you enjoy visiting",
        "Describe a city that you have visited and enjoy going to.",
        ["where the city is", "what you did there", "how many times you have visited", "why you enjoy it"],
        "Would you like to live in this city?",
    ),
    _card(
        "a clever solution to a problem",
        "Describe a time when someone you know found a clever solution to a problem.",
        ["who the person is", "what the problem was", "how they solved it", "why the solution was clever"],
        "Could you have found the same solution yourself?",
    ),
    _card(
        "a person who protects nature",
        "Describe a person who encourages others to protect the environment or nature.",
        ["who this person is", "how they encourage others", "how long they have done this", "how you feel about their work"],
        "Has this person changed any of your habits?",
    ),
    _card(
        "encouraging someone to do something",
        "Describe a time when you encouraged someone to do something they did not want to do.",
        ["who the person was", "what you encouraged them to do", "how they reacted", "why you encouraged them"],
        "Was this person pleased with the result?",
    ),
]


PDF_PART3_QUESTION_SETS = {
    "food eaten on a special occasion": [
        "What are the differences between what people eat now and in the past?",
        "Why do people eat special foods at festivals or on special occasions?",
        "How is festival food different from everyday food?",
        "Do people prefer eating out or eating at home?",
        "What kinds of food are popular in your country?",
        "Do people in your country grow food at home?",
    ],
    "a difficult decision with a good result": [
        "What kinds of important decisions do young people have to make?",
        "Who are the best people to help teenagers make important decisions?",
        "Should children be allowed to make some decisions themselves?",
        "How do other young people influence teenagers' decisions?",
        "How does advertising influence people's everyday decisions?",
        "Does having too much information online make decisions more difficult?",
    ],
    "a person with a medical career": [
        "Why do some people want to become doctors?",
        "Is it difficult to become a doctor?",
        "Why do some children want to become doctors?",
        "Do children find learning biology interesting?",
        "Can studying biology at school help students become healthier?",
    ],
    "a good place to live": [
        "What types of places do people like to live in?",
        "What are the advantages of living near one's workplace?",
        "How do the places preferred by older and younger people differ?",
        "Why do some people move to a different area?",
        "What preparations should people make before moving?",
        "Is choosing where to live one of life's most important decisions?",
    ],
    "a tall building you like or dislike": [
        "What are the disadvantages of living in tall buildings?",
        "Will there be more tall buildings in the future?",
        "Why do many people choose to live in tall buildings?",
        "Why do some people choose to design their own homes?",
        "What are the advantages of living in a high-rise building?",
        "Will more people live in high-rise buildings in the future?",
        "How does climate affect building design?",
    ],
    "a successful businessperson": [
        "What kinds of businesses have recently emerged in your city?",
        "Why do some people prefer small shops to large supermarkets?",
        "Is the quality of products in small shops the same as in large supermarkets?",
        "Is it easy or difficult to achieve success in business in your country?",
        "Why do some people fail when starting a business?",
        "What are the key factors in business success?",
    ],
    "a person who enjoys growing plants": [
        "Why do some people like keeping plants at home?",
        "Should schools teach children how to grow plants?",
        "Do people in your country enjoy growing plants?",
        "Why do people grow fruit and vegetables themselves?",
        "Will people grow more of their own food in the future?",
    ],
    "a live sports match": [
        "What kinds of sports are popular in your country?",
        "What sports competitions do children usually take part in?",
        "Do people prefer watching sports live or on television?",
        "How is watching live sport different from watching it on television?",
    ],
    "a piece of local news": [
        "Do people read newspapers where you live?",
        "Are people more interested in local news than national news?",
        "Why do some people become very involved in their community?",
        "Were local communities stronger in the past?",
        "Is it important to have a national identity?",
        "How can people develop their national identity?",
    ],
    "a technology problem": [
        "What technology products do people use at home?",
        "What are the advantages and disadvantages of students using technology?",
        "Are young children too reliant on technology?",
        "Should parents limit their children's screen time?",
        "Why do many young people spend so much time looking at screens?",
        "Can relying on technology prevent children from learning useful skills?",
    ],
    "getting up very early": [
        "Why do people get up early?",
        "Why do many people dislike getting up early?",
        "Is early morning the best part of the day?",
        "What are the advantages of arriving early for an appointment?",
        "When might arriving very early be inconvenient?",
        "Why do some people think punctuality is important while others do not?",
    ],
    "a home you liked visiting but would not live in": [
        "How frequently do people in your country visit each other's homes?",
        "What do people usually bring when visiting someone's home?",
        "How are homes in the countryside different from homes in cities?",
        "Why might an attractive home still be unsuitable for daily life?",
    ],
    "a long-held ambition": [
        "What kinds of ambitions do young people have?",
        "What kinds of ambitions do children have?",
        "Is ambition necessary within a company team?",
        "Do people need ambition in their careers?",
        "Should parents interfere with their children's ambitions?",
        "Why should parents encourage children to have ambitions?",
    ],
    "a childhood friend": [
        "How do children usually make friends?",
        "Is it easy for children to make friends?",
        "Do adults benefit from having older friends?",
        "What are the benefits of having an older friend?",
        "Can friendships last a lifetime?",
    ],
    "a time you changed your plans": [
        "What are common reasons for changing plans?",
        "Do young people like changing plans?",
        "What kinds of plans need to be practical?",
        "How should people tell friends that a plan must change?",
        "Do older people change plans often?",
    ],
    "an interesting social-media video": [
        "What types of videos do younger and older people prefer?",
        "How is learning through videos different from learning through books?",
        "What skills can people learn from videos?",
        "What are the advantages of online learning?",
    ],
    "a time you changed your opinion": [
        "Do children often change their opinions?",
        "When do people change their opinions?",
        "Who do young people turn to for advice?",
        "Do people enjoy expressing opinions about politics?",
    ],
    "a holiday place you recommend": [
        "What attractions are popular with tourists in your country?",
        "Do younger and older people choose different holiday destinations?",
        "What do people consider when making travel plans?",
        "How do people get to know a new place?",
        "How do people decide when to take a holiday?",
        "What are the advantages and disadvantages of planning every detail in advance?",
    ],
    "a place where you felt bored": [
        "Why might young people find conversations with elderly people boring?",
        "Why do students sometimes find lessons boring?",
        "How can teachers make lessons less boring?",
        "Why do some children find education boring?",
        "When do people feel bored?",
        "What can people do when they feel bored?",
    ],
    "a person who achieved something difficult": [
        "Who are some successful people in your country?",
        "Does earning a lot of money mean someone is successful?",
        "How should success be defined?",
        "Should people set goals for themselves?",
        "Are successful people sometimes lonely?",
    ],
    "an environmental protection law": [
        "Why should children learn to follow rules from an early age?",
        "Should schools have more rules or fewer rules?",
        "Why are rules important for young children?",
        "What kinds of rules do schools have in your country?",
        "Why does society need laws?",
        "Should people who break the law always be punished?",
    ],
    "an important decision made slowly": [
        "What important decisions should people make slowly?",
        "Why do some people decide quickly while others take more time?",
        "Do children ever have to make important decisions?",
        "What important decisions do teenagers make after graduation?",
        "Who can children ask for help when making decisions?",
        "Can advertisements influence people's shopping decisions?",
    ],
    "giving a talk to many people": [
        "What benefits has the internet brought to communication?",
        "Is it better to be a good speaker or a good listener?",
        "What qualities does a good communicator need?",
        "Why do some people dislike communicating through the internet?",
    ],
    "doing something with other people": [
        "Should children learn to work in teams?",
        "What kinds of group work do children do at school?",
        "Why do some people prefer solving problems alone?",
        "What problems might a team leader face?",
        "What qualities does a good leader need?",
    ],
    "an animal story": [
        "Do many people in your country keep pets?",
        "What animals do people in your country keep as pets?",
        "Should keeping pets be banned in cities?",
        "Should schools teach children about animals?",
    ],
    "a person who did not reply to your message": [
        "Why do people sometimes not reply to messages?",
        "How can people show respect when replying to messages?",
        "Are eye contact and body language more important than words?",
        "Should people expect others to reply immediately?",
    ],
    "an advertisement featuring a famous person": [
        "Where do advertisements usually appear?",
        "What are the advantages and disadvantages of advertising?",
        "Is using celebrities in advertisements effective?",
        "How can consumers tell whether an advertisement is trustworthy?",
    ],
    "a person who is good at learning languages": [
        "Do people in your country learn foreign languages?",
        "How can people learn a new language effectively?",
        "Is learning another language necessary for study or work?",
        "How do adults and children learn languages differently?",
        "Is it useful to learn a language only for travelling?",
    ],
    "a family member who made you proud": [
        "What behaviours of children make parents proud?",
        "Can academic prizes motivate children?",
        "Should parents give children many prizes or rewards?",
        "Does every job give people a sense of pride?",
        "Have the things people feel proud of changed over time?",
        "When do adults feel proud of themselves?",
    ],
    "a time you could not use your phone": [
        "In which places should people not use phones?",
        "Do we need new rules governing mobile-phone use?",
        "How do younger and older people use phones differently?",
        "When should children be allowed to own phones?",
        "Were social rules stricter in the past?",
        "How common is mobile-phone addiction?",
    ],
    "a perfect future job": [
        "What jobs do children usually want to do?",
        "What are common dream jobs in your country?",
        "Why do some jobs attract more people than others?",
        "Why do people's dream jobs change as they grow older?",
        "Is money the main factor when choosing a job?",
        "Why do some people not want to work hard?",
        "How do coworkers influence people's work habits and performance?",
    ],
    "an occasion when many people smiled": [
        "Why do people smile?",
        "Do children smile more frequently than adults?",
        "Why do people smile when taking photographs?",
        "Do older people control their emotions better than younger people?",
        "When is it important not to show emotions?",
        "Are people more strongly motivated by emotions or logic?",
    ],
    "a famous person you would like to meet": [
        "What kinds of famous people appear in the news in your country?",
        "Why do children want to become famous?",
        "Are there more celebrities in the news now than in the past?",
        "Does everyone enjoy reading celebrity news?",
        "Do people prefer manufactured celebrities or people with genuine talent?",
        "Can people become famous without talent?",
        "Would people still want fame if they understood its disadvantages?",
    ],
    "a person who enjoys helping others": [
        "What machines help people with housework?",
        "Should parents teach children to help with housework?",
        "How can children help their parents at home?",
        "Should every family member help at home?",
        "Should students do community service?",
        "What help do people need when starting a new job?",
        "Should employees ask managers for help?",
        "Will artificial intelligence cause many people to lose their jobs?",
    ],
    "a useful program or app": [
        "What programs or apps are popular in your country?",
        "Why do some people dislike using apps?",
        "How do the apps used by younger and older people differ?",
        "Should parents limit children's time on apps?",
        "What are the benefits of using apps in education?",
    ],
    "a movie you enjoyed": [
        "What kinds of movies are popular in your country?",
        "Do people prefer watching movies at home or in the cinema?",
        "Why do some people not enjoy watching movies?",
        "What qualities do good actors need?",
        "Which matters more for an actor, skill or appearance?",
        "Is being an actor a difficult job?",
        "How important are famous actors to a film's success?",
    ],
    "a time you used your imagination": [
        "What games require children to use their imagination?",
        "Should teachers encourage children to use their imagination?",
        "Does reading require more imagination than watching cartoons?",
        "What jobs require a good imagination?",
        "Do scientists need to use imagination?",
    ],
    "an interesting road trip": [
        "Are bicycles and motorbikes popular in your country?",
        "Which vehicles are most popular in your country?",
        "What is the best feature of public transport where you live?",
        "Why do more people want to buy cars?",
        "How does travel differ between cities and the countryside?",
        "Do city planners consider pedestrians' needs enough?",
        "How can an inadequate transport system affect a country?",
    ],
    "a quiet place you enjoyed visiting": [
        "What quiet places do people in your country visit?",
        "Why do some people dislike quiet places?",
        "Are there fewer quiet places now than in the past?",
        "Can a place ever be completely quiet?",
        "Can people listen to music while doing other tasks?",
        "How does quietness benefit people?",
        "Why do some people feel uncomfortable when there is no noise?",
    ],
    "a person who learned without a teacher": [
        "What can children learn from their parents?",
        "What subjects do children enjoy at school?",
        "Do children have to study too many subjects?",
        "How strongly do parents influence children's behaviour?",
        "Can a good teacher make learning more interesting?",
        "Why might adults return to education?",
        "Should retired people return to full-time education?",
        "Should companies provide regular training for employees?",
    ],
    "a person who is good at planning": [
        "What plans do people make with friends and family?",
        "Why is planning important for special events?",
        "Why do some people dislike planning their social life in advance?",
        "How does career planning benefit young people?",
        "Whom should young people ask for career advice?",
        "Is careful planning essential for a successful career?",
    ],
    "a child who enjoys painting or drawing": [
        "At what age can children start drawing?",
        "Should children have art lessons at school?",
        "Why do children draw more often than adults?",
        "Why do people enjoy visiting art galleries and museums?",
        "Should entry to galleries and museums be free?",
        "What can people learn about life by looking at art?",
    ],
    "a good place for shopping": [
        "Where do people like to shop in your country?",
        "Has shopping become a hobby for many people?",
        "Do people waste too much time shopping?",
        "Why do people buy things they do not need?",
        "Does buying things make people happy?",
        "How much does advertising influence shoppers?",
    ],
    "working briefly in another country": [
        "What short-term jobs can people do abroad?",
        "How does working abroad briefly benefit young people?",
        "Why might some people not want to work abroad?",
        "What are the advantages of working for an international company?",
        "What personal skills are needed to work internationally?",
        "Is practical experience more useful than qualifications in international work?",
    ],
    "a time you gave advice": [
        "When is it better to ask friends rather than family for advice?",
        "Why do older people sometimes ask younger people for advice?",
        "What problems arise from asking too many people for advice?",
        "When should people think carefully before giving advice?",
        "What personal qualities are needed to give good advice?",
        "Can anyone learn to give advice effectively?",
    ],
    "technology you would like to buy": [
        "What types of technology do young people use?",
        "Does technology have a positive effect on young people's lives?",
        "Is spending a lot of time online healthy?",
        "How does talking online differ from talking face to face?",
        "Can people make good friends online?",
        "How can technology affect family relationships?",
    ],
    "an event with music you disliked": [
        "What music events are popular in your country?",
        "What do people enjoy about large music events?",
        "Why might younger and older people prefer different music events?",
        "Should children have music lessons at school?",
        "Why is music played during physical exercise?",
        "Does playing music in shops encourage customers to buy more?",
    ],
    "a TV or online programme": [
        "What television or online programmes are popular in your country?",
        "Do younger and older people enjoy similar programmes?",
        "Why do some people spend so much time watching programmes?",
        "What makes a programme popular?",
        "Are there too many programmes to choose from?",
        "Should parents choose what programmes their children watch?",
    ],
    "paying more than expected": [
        "What do young people like spending money on?",
        "Why do people buy things they do not really need?",
        "How important is saving money for the future?",
        "Should children learn to donate money to people in need?",
        "Should rich people give some money to help others?",
        "How else can people support those in need?",
    ],
    "a city you enjoy visiting": [
        "Why do tourists choose certain cities?",
        "Are modern cities more interesting than historical cities?",
        "Are popular tourist cities also good places to live?",
        "Why do many people choose to live in cities?",
        "Does city life benefit younger or older people more?",
        "Do cities lose their individual character as they grow?",
    ],
    "a clever solution to a problem": [
        "Are children born clever, or do they learn to be clever?",
        "How do schools help children become more intelligent?",
        "Are very clever children usually happy?",
        "Why can a person excel at one thing but not another?",
        "Why does society need different types of intelligence?",
        "Can people become good at anything if they try hard enough?",
    ],
    "a person who protects nature": [
        "How can parents help children learn about nature?",
        "Should children spend more time learning about nature at school?",
        "Can children living in cities easily enjoy the natural world?",
        "What can individuals do to protect nature?",
        "Do we need new laws to protect nature?",
        "Are punishments or rewards more effective in protecting nature?",
    ],
    "encouraging someone to do something": [
        "When do parents need to encourage children to do something?",
        "How can parents encourage children to do unwanted tasks?",
        "Why do children resist what their parents ask them to do?",
        "How can employees be encouraged to work hard?",
        "Is encouraging employees a boss's most important role?",
        "Are workers more motivated by praise or money?",
    ],
}


for _cue_card in PDF_CUE_CARDS:
    _cue_card["part3"] = list(
        PDF_PART3_QUESTION_SETS.get(_cue_card["title"], DEFAULT_PART3_FALLBACK)
    )
